### ISSUE TITLE
DPA flag in json

### ISSUE THREAD

**Issue by thekarinka** [iqrfsdk/jlibiqrf#6]
How to solve DPA flag in json data?

Possible problems discussed in email
- bridge can receive async packet and need to know how to solve it

-- maybe set this flag in config?

-- or I suggest some storage object, which takes this flag from received data and put it to outgoing packet (async too)

**Comment by spinarr** [comment]
How is the decision made that async packet from IQRF network is treated as DPA paket (req/resp)?
The packet could be anything and only user knows her/his own system.

**Comment by thekarinka** [comment]
Maybe it could be better, if this value could contain some enum of values instead of true or false.
Some states like:
DPA_Packet
Non_DPA_Packet
Async_Packet

But implementation of this logic is relatively big invervention into system and it needs carefully consideration. Maybe it could solve similar logic like for convertors - user can use some implementation from us or use own implementation.
